# Generated by Django 5.0.2 on 2025-03-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='events',
            field=models.ManyToManyField(related_name='students', to='institution_app.event'),
        ),
    ]
