# Generated by Django 5.0.2 on 2025-03-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution_app', '0002_student_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
