# Generated by Django 5.0.2 on 2025-03-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_app', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team_size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
