# Generated by Django 5.0.2 on 2025-03-28 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_app', '0005_event_team_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='institution_app.event')),
                ('members', models.ManyToManyField(related_name='teams', to='institution_app.student')),
            ],
        ),
    ]
