# Generated by Django 4.2 on 2025-11-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_app', '0007_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.PositiveIntegerField(),
        ),
    ]
