# Generated by Django 4.2 on 2025-11-20 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_app', '0008_alter_student_phone_alter_student_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'Phone number must be 10–15 digits.')]),
        ),
    ]
