# Generated by Django 5.0.2 on 2025-03-28 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Victrix_app', '0001_initial'),
        ('staff_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='institution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='Victrix_app.staff'),
        ),
    ]
