# Generated by Django 5.0.2 on 2025-03-28 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Victrix_app', '0001_initial'),
        ('staff_app', '0003_alter_institution_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='Victrix_app.staff'),
        ),
    ]
